### ISSUE TITLE
Ubuntu Build Error (Python 3.6)

### ISSUE THREAD

**Issue by gwortmann** [luigifcruz/CyberRadio#3]
Collecting pyqt5 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-2s5fdls5/pyqt5/setup.py'

**Comment by luigifcruz** [comment]
Hey, thanks for reporting this unexpected behavior. This is probably a PyQt5 error. Try to install an older version:
```
pip3 install pyqt5==5.13.2
```

**Comment by gwortmann** [comment]
Hi Luigi,
thanks for the fast reply - you are right.
It seems, that there is a general issue with PyQt5 Installtion on my Nvidia Jetson Nano machine.
